#!/bin/sh
prevMsg=$(git log -1 --pretty=%B | cat)
shouldTag=$(python .git/hooks/post_commit.py "$prevMsg")

if [[ $shouldTag == *"NO"* ]]; then
  :
else
  git tag -a $shouldTag -m "Version $shouldTag Release"
  ssh-agent bash -c 'ssh-add $SSH_KEY; git push --tags'
fi
